### ISSUE TITLE
ActiveSupport Gem is restricted to less than 7.0.0

### ISSUE THREAD

**Issue by cdhagmann** [synvert-hq/synvert-core-ruby#288]
I am trying to use `synvert` in a Rails 7.1 application but it is forces me to use version 0.20.0. This is because in `synvert-core-ruby` has restricted the ActiveSupport gem to less than version 7.0.0 since version 1.6.

https://github.com/synvert-hq/synvert-core-ruby/blob/v1.6.0/synvert-core-ruby.gemspec

**Comment by flyerhzm** [comment]
@cdhagmann I just released synvert-core version 2.0.1, which does not restrict activesupport version anymore.
